export enum Role {
  COLLABORATEUR = 'COLLABORATEUR',
  RESPONSABLE = 'RESPONSABLE',
  EXPERT_COMPTABLE = 'EXPERT_COMPTABLE',
  ADMIN = 'ADMIN',
}

export enum TypeEntite {
  PERSONNE_PHYSIQUE = 'PERSONNE_PHYSIQUE',
  PERSONNE_MORALE = 'PERSONNE_MORALE',
}

export enum StatutKanban {
  PRISE_CONTACT = 'PRISE_CONTACT',
  DECOUVERTE = 'DECOUVERTE',
  OPPORTUNITE = 'OPPORTUNITE',
  LAB = 'LAB',
  PREPARATION = 'PREPARATION',
  CONVERTI = 'CONVERTI',
  REFUSE = 'REFUSE',
}

export enum StatutClient {
  ACTIF = 'ACTIF',
  INACTIF = 'INACTIF',
  RESILIE = 'RESILIE',
}

export enum StatutKyc {
  INCOMPLET = 'INCOMPLET',
  COMPLET = 'COMPLET',
  VALIDE = 'VALIDE',
  EXPIRE = 'EXPIRE',
}

export enum ScreeningStatut {
  NON_EFFECTUE = 'NON_EFFECTUE',
  OK = 'OK',
  ALERTE = 'ALERTE',
}

export enum NiveauRisque {
  FAIBLE = 'FAIBLE',
  MOYEN = 'MOYEN',
  ELEVE = 'ELEVE',
}

export enum TypeDocument {
  PIECE_IDENTITE = 'PIECE_IDENTITE',
  JUSTIFICATIF_DOMICILE = 'JUSTIFICATIF_DOMICILE',
  KBIS = 'KBIS',
  STATUTS = 'STATUTS',
  LISTE_UBO = 'LISTE_UBO',
  ATTESTATION_PPE = 'ATTESTATION_PPE',
  JUSTIFICATIF_FONDS = 'JUSTIFICATIF_FONDS',
  LETTRE_MISSION = 'LETTRE_MISSION',
  RAPPORT = 'RAPPORT',
  ANNEXE = 'ANNEXE',
  AUTRE = 'AUTRE',
}

export enum TypeMission {
  COMPTABILITE = 'COMPTABILITE',
  AUDIT = 'AUDIT',
  CONSEIL = 'CONSEIL',
  JURIDIQUE = 'JURIDIQUE',
  AUTRE = 'AUTRE',
}

export enum StatutMission {
  EN_COURS = 'EN_COURS',
  SUSPENDUE = 'SUSPENDUE',
  TERMINEE = 'TERMINEE',
  RESILIEE = 'RESILIEE',
}

export enum TypeObligation {
  KYC_VERIFICATION = 'KYC_VERIFICATION',
  EVALUATION_RISQUE = 'EVALUATION_RISQUE',
  MISE_A_JOUR_DOCS = 'MISE_A_JOUR_DOCS',
  VALIDATION_RELATION = 'VALIDATION_RELATION',
  LETTRE_MISSION = 'LETTRE_MISSION',
}

export enum StatutObligation {
  A_FAIRE = 'A_FAIRE',
  FAIT = 'FAIT',
  EN_RETARD = 'EN_RETARD',
  EXPIRE = 'EXPIRE',
}

export enum TypeOperationSensible {
  SANS_JUSTIFICATION = 'SANS_JUSTIFICATION',
  COMPLEXE = 'COMPLEXE',
  SANS_OBJET_LICITE = 'SANS_OBJET_LICITE',
  INHABITUELLE = 'INHABITUELLE',
  ECONOMIE_VIRTUELLE = 'ECONOMIE_VIRTUELLE',
  ESPECES = 'ESPECES',
  AUTRE = 'AUTRE',
}

export enum StatutOperationSensible {
  SIGNALEE = 'SIGNALEE',
  EN_ANALYSE = 'EN_ANALYSE',
  CLASSEE = 'CLASSEE',
  TRACFIN_DECLARE = 'TRACFIN_DECLARE',
}

export enum TypeContact {
  INTERVENANT = 'INTERVENANT',
  AVOCAT = 'AVOCAT',
  COMMISSAIRE_COMPTES = 'COMMISSAIRE_COMPTES',
  NOTAIRE = 'NOTAIRE',
  AUTRE = 'AUTRE',
}

export enum TypePlanningEtape {
  REGLEMENTAIRE = 'REGLEMENTAIRE',
  MANUELLE = 'MANUELLE',
}

export enum StatutPlanningEtape {
  A_FAIRE = 'A_FAIRE',
  EN_COURS = 'EN_COURS',
  FAIT = 'FAIT',
  ANNULEE = 'ANNULEE',
}
